adapter_iface='org.bluez.Adapter1'
bluez_service='org.bluez'
bus_path='/org/bluez'
obex_service="org.bluez.obex"
obex_client="org.bluez.obex.Client1"
agent_path="/test/agent"
agent_interface = "org.bluez.Agent1"
agent_manager_iface="org.bluez.AgentManager1"
obex_obj_push="org.bluez.obex.ObjectPush1"
obex_obj_transfer="org.bluez.obex.Transfer1"
device_iface="org.bluez.Device1"
obj_iface="org.freedesktop.DBus.ObjectManager"
props_iface="org.freedesktop.DBus.Properties"
media_iface="org.bluez.MediaControl1"
dbus_command = "/usr/local/bluez/dbus-1.12.20/bin/dbus-daemon --system --nopidfile"
bluetoothd_command = '/usr/local/bluez/bluez-tools/libexec/bluetooth/bluetoothd -nd --compat'
pulseaudio_command = '/usr/local/bluez/pulseaudio-13.0_for_bluez-5.65/bin/pulseaudio -vvv'
hcidump_command = "/usr/local/bluez/bluez-tools/bin/hcidump -i {interface} -Xt"
hciconfig_up_command = "hciconfig {interface} up"